# Generated by Django 4.2.7 on 2023-11-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='consulta',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='historialMascotas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.historialmascotas'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='vacuna',
            field=models.CharField(max_length=100, null=True, verbose_name='vacuna;'),
        ),
    ]
