# Generated by Django 4.2.7 on 2023-11-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numDocPersona',
            field=models.IntegerField(null=True, verbose_name='Numero de Documento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipodocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipodocumento'),
        ),
    ]
