# Generated by Django 4.2.7 on 2023-11-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_numero_documento_usuario_sexo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
