# Generated by Django 4.2.7 on 2023-12-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_nombres_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
