# Generated by Django 4.2.7 on 2023-12-01 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='id',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='numeroOrden',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.persona'),
        ),
    ]
